### ISSUE TITLE
getMeetings fails due to localized date string

### ISSUE THREAD

**Issue by mgallecom** [Tylopilus/jira-timebooker#1]
Start and and dates of the meetings can only be calculated if the date string by outlook is in english.
Localized outlook will lead to a failure of reading meetings

**Comment by Tylopilus** [comment]
This issue has been addressed with newest release.

Reference commit: https://github.com/Tylopilus/jira-timebooker/commit/2f4fc4e4b3a6d93b96961738419554d88dbbf9cb
